### ISSUE TITLE
Invalid character (&) in collectcells output

### ISSUE THREAD

**Issue by youngmd** [WIYN-ODI/QuickReduce#16]
podi_collectcells can be set to base output filenames on header keywords.  It appears that a number of invalid characters are checked for and replaced with an underscore, but the ampersand (&) is not included in the current checks.  While the ampersand is a valid character in filenames, it breaks subsequent command-line scripted operations on the output file (i.e., ingestion back into PPA).

**Comment by rkotulla** [comment]
addressed and fixed in commit e28ff2e2e6d4c2ef0ae608aa24a79c64a710353a
